apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: g1qpzc97q-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: g1qpzc97q-go 
  name: g1qpzc97q-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: g1qpzc97q-go 
