apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: g1qpzc97q-go 
  janus-idp.io/tekton: g1qpzc97q-go
  backstage.io/kubernetes-id: g1qpzc97q-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: g1qpzc97q-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml